# Configuration for the academic manuscript format
project:
  type: manuscript  # Uses manuscript-specific layout and formatting
  output-dir: _manuscript  # Separate from book output

# Execute settings for manuscript
execute:
  freeze: auto  # Cache execution results
  echo: false   # Hide code chunks in academic output

# Define manuscript formats
format:
  # HTML for browser preview
  html:
    toc: true
    toc-depth: 3
    number-sections: true
  #  css: styles/manuscript.css   # to be excluded as the file does not exist! has to be added later?
    html-math-method: katex
    
  # PDF with university formatting
  pdf:
    documentclass: report  # University requires report format
    classoption: [12pt, a4paper, oneside]
    template: latex/template.tex  # Custom university template
    include-in-header: latex/preamble.tex
    pdf-engine: lualatex
    keep-tex: true  # Keep LaTeX for Overleaf
    output-file: thesis-manuscript.pdf  # Clear filename
    toc: true
    lot: true  # List of tables
    lof: true  # List of figures
    colorlinks: true
    
  # LaTeX output for direct editing
  latex:
    documentclass: report
    include-in-header: latex/preamble.tex
    output-file: thesis-manuscript.tex

# Manuscript-specific settings
manuscript:
  article: thesis.qmd  # Main entry point for manuscript
#  title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
#  subtitle: "An Epistemic Framework for Leveraging Frontier AI Systems to Upscale Conditional Policy Assessments in Bayesian Networks on a Narrow Path towards Existential Safety"
#  author:
#    - name: "Valentin Jakob Meyer"
#    - name: "Prof. Dr. Timo Speith" 
#      role: "Supervisor"