project:
  type: manuscript
  output-dir: manuscript/_docs   # keeps root tidy


execute:
  freeze: auto

format:
  html:
    toc: true
    comments:
      hypothesis: true
  docx: default
  jats: default
  agu-pdf: default



