project:
  type: default
  output-dir: _output
  # Use preview to avoid rebuilding everything during development
  preview:
    port: 4200
    browser: false

# Shared execution settings
execute:
  freeze: auto  # Cache execution results

# Enable profiles for different output types
profiles:
  # Book format for interactive reading
  book:
    project:
      type: book
      output-dir: _book
    book:
      title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
      author: "Valentin Jakob Meyer"
      date: "2025-05-26"
      search: true
      repo-url: https://github.com/VJMeyer/submission
      repo-actions: [edit]
      downloads: [pdf, epub, tex]
      sharing: [twitter, facebook]
      chapters:
        - index.qmd
        - article/chapters/Frontmatter.qmd
        - article/chapters/Introduction.qmdwerne
        - article/chapters/Context.qmd
        - article/chapters/AMTAIR.qmd
        - article/chapters/Discussion.qmd
        - article/chapters/Conclusion.qmd
        - article/ref/references.qmd
        - article/chapters/Appendices.qmd
        - article/chapters/appendixA.qmd
    format:
      html:
        theme: cosmo
        code-fold: true
        toc: true
        toc-depth: 3
      pdf:
        documentclass: book
        template: article/latex/template.tex
        include-in-header: article/latex/preamble.tex
        keep-tex: true
        output-file: thesis-book.pdf
      latex:
        documentclass: book
        include-in-header: article/latex/preamble.tex
        output-file: thesis-book.tex

  # Manuscript format for academic submission
  manuscript:
    project:
      type: manuscript
      output-dir: _manuscript
    execute:
      echo: false
    manuscript:
      article: article/thesis.qmd
    format:
      html:
        toc: true
        toc-depth: 3
        number-sections: true
      pdf:
        documentclass: report
        classoption: [12pt, a4paper, oneside]
        template: article/latex/template.tex
        include-in-header: article/latex/preamble.tex
        pdf-engine: lualatex
        keep-tex: true
        output-file: thesis-manuscript.pdf
        toc: true
        lot: true
        lof: true
        colorlinks: true
      latex:
        documentclass: report
        include-in-header: article/latex/preamble.tex
        output-file: thesis-manuscript.tex

# Shared bibliography configuration
bibliography: article/ref/MAref.bib