project:
  type: book
  output-dir: _docs   # keeps root tidy

#toc: true

profiles:
  manuscript:
    project:
      type: manuscript
      output-dir: article/_docs   # keeps root tidy
    execute: false          # e.g. re-use cached code
    format:
      pdf:
        template: journal.cls

book:
  title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
  author: "Valentin Jakob Meyer"
  date: "5/1/2025"
  search: true
  repo-url: https://github.com/VJMeyer/submission
  repo-actions: [edit]
  downloads: [pdf, epub]     # vs markdown, html etc.
  sharing: [twitter, facebook]
  cover-image: article/images/cover.png
  chapters:
    - index.qmd
    - article/chapters/Introduction.qmd
    - article/chapters/Context.qmd
    - article/chapters/AMTAIR.qmd
    - article/chapters/Discussion.qmd
    - article/chapters/Conclusion.qmd
    - article/chapters/intro.qmd
    - article/chapters/summary.qmd
    - article/chapters/OutlineDraft9.2.qmd
    - article/chapters/Draft9.2_sec2.3-4.4_feedback.qmd
#    - article/chapters/intro.qmd
#    - article/chapters/01-intro.qmd
#    - article/chapters/02-methods.qmd
#    - article/chapters/03-results.qmd
    - article/chapters/appendixA.qmd
#    - article/chapters/methodology.qmd
    # etc.
    - article/ref/references.qmd

#  appendices:
#    - tools.qmd
#    - resources.qmd
  page-footer: 
    left: "Copyright 2025, Valentin Meyer" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/

bibliography: article/ref/MAref.bib

format:
  html:
    theme: cosmo
    code-fold: true

  pdf:
    pdf-engine: lualatex
    pdf-engine-opt: "-shell-escape"
#    template-partials:
#      - latex/journal-template.tex
#    include-in-header:
#      latex/pdfx-setup.tex     # loads \usepackage[a-2b]{pdfx}
#      latex/preamble.tex    # Claude suggestion
#    documentclass: scrreprt    # Claude suggestion
#    keep-tex: true            # Claude suggestion
#    documentclass: book    # Claude suggestion
#    template: latex/template.tex    # Claude suggestion

  latex: default             # emits .tex on demand