





# # SWITCH BETWEEN BOOK AND MAUSCRIPT QUARTO BY (UN-)COMMENTING THE RESPECTIVE SECTION IN THIS _quarto.yml file






# project:
#   type: book
#   output-dir: _outputs/book

# execute:
#   freeze: auto

# book:
#   title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
#   author: "Valentin Jakob Meyer"
#   date: "2025-05-26"
#   search: true
#   repo-url: https://github.com/VJMeyer/submission
#   repo-actions: [edit]
#   downloads: [pdf, epub] #tex?
#   sharing: [twitter, facebook]
#   cover-image: images/cover.png
#   output-file: "complete-book"
#   chapters:
#     - index.qmd
#     - chapters/Frontmatter.qmd
#     - chapters/Introduction.qmd
#     - chapters/Context.qmd
#     - chapters/AMTAIR.qmd
#     - chapters/Discussion.qmd
#     - chapters/Conclusion.qmd
#     - ref/references.qmd
#   appendices:
#     - chapters/Appendices.qmd
#     - chapters/appendixA.qmd
#   navbar:
#     pinned: true
#   page-footer: 
#     left: "Copyright 2025, Valentin Meyer" 
#     right: 
#       - icon: github
#         href: https://github.com/
#       - icon: twitter 
#         href: https://twitter.com/

# format:
#   html:
#     theme: cosmo
#     code-fold: true
#     toc: true
#     toc-depth: 5
#     toc-title: "ToC"
#     page-navigation: true
#     site-path: /
#     self-contained: false
#     number-sections: true
#   pdf:
#     documentclass: book
#     geometry: margin=1in
#     template: latex/template.tex
#     include-in-header: latex/preamble.tex
#     keep-tex: true
#     toc: true
#     pdf-engine: xelatex
#     output-file: thesis-book.pdf
#   latex:
#     documentclass: book
#     include-in-header: latex/preamble.tex
#     output-file: thesis-book.tex
#     keep-tex: true

# bibliography: ref/MAref.bib









# Master configuration file for thesis project
# Controls rendering formats and options

# Configure which profile to use by uncommenting ONE of these sections
# Then run: quarto render

# BOOK PROFILE - Interactive HTML with navigation
project:
  type: manuscript  # manuscript format for formal thesis
  output-dir: _outputs/manuscript  # Output directory for manuscript format

execute:
  freeze: auto  # Caches results for faster rendering
  echo: false  # Hide code by default

# Configure manuscript settings
manuscript:
  article: thesis.qmd  # Main entry point file
  notebooks:  # Include notebooks
    - notebook: notebooks/AMTAIR_Prototype_example_carlsmith.ipynb
      title: AMTAIR Carlsmith Example
    #  url:  

# Output format configuration
format:
  # HTML output settings
  html:
    toc: true  # Include table of contents
    toc-depth: 5  # Depth of TOC headings
    number-sections: true  # Number sections in output
    site-path: /  # Base path for site
  
  # PDF output settings
  pdf:
    documentclass: report  # Academic report format
    classoption: [12pt, a4paper, oneside]  # Paper and font options
    template: latex/template.tex  # Custom template
    include-in-header: latex/preamble.tex  # LaTeX preamble
    pdf-engine: xelatex  # Engine for PDF creation
    keep-tex: true  # Keep LaTeX source
    output-file: thesis-manuscript.pdf  # Output filename
    toc: true  # Include table of contents
    lot: true  # List of tables
    lof: true  # List of figures
    colorlinks: true  # Colored hyperlinks
  
  # LaTeX source output
  latex:
    documentclass: report  # Academic report format
    include-in-header: latex/preamble.tex  # LaTeX preamble
    output-file: thesis-manuscript.tex  # Output filename

# Bibliography configuration
bibliography: ref/MAref.bib  # Reference file location