project:
  type: book
  output-dir: _outputs/book

execute:
  freeze: auto
  echo: true
  warning: false
  error: false

book:
  title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
  subtitle: "An Epistemic Framework for Leveraging Frontier AI Systems to Upscale Conditional Policy Assessments in Bayesian Networks on a Narrow Path towards Existential Safety"
  author: "Valentin Jakob Meyer"
  date: "2025-05-26"
  search: true
  repo-url: https://github.com/VJMeyer/submission
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  cover-image: images/cover.png
  # page-footer: "Copyright 2021, Norah Jones"
  # page-footer: 
  #   left: "Copyright 2025, Valentin Meyer --- <!-- [ ] Consider adding a footer-->" 
  #   border: false
  #   background: light
  #   right: 
  #     - icon: github
  #       href: https://github.com/
  #     - icon: twitter 
  #       href: https://twitter.com/ 
  chapters:
    - index.qmd
    # - chapters/Outlines/Outline_12.2.qmd
    # - chapters/Outlines/Outline_11.7.qmd
    # - chapters/code_improve/Code-Improvement-Plan_12.2.qmd
    # - chapters/code_improve/Code-Improvement-Plan_11.7.qmd
    - chapters/0.Frontmatter.qmd
    - chapters/1.Introduction.qmd
    - chapters/2.0.Context.qmd
    - chapters/3.0.AMTAIR.qmd
    - chapters/4.Discussion.qmd
    - chapters/5.Conclusion.qmd
    - ref/references.qmd
  appendices:
    - chapters/I.Appendices.qmd
    - AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb

# notebook-view:
#   - notebook: AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb
#     title: "Plots and Computations"
#     url: https://colab.research.google.com/drive/12GsIPQ644SI4vkEEHiZn-Qqfbr-bD1__

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    toc-depth: 5
    number-sections: true
    code-links:
      - text: Colab Notebook (Manual Link in .yml)
        icon: file-code
        href: https://colab.research.google.com/github/VJMeyer/submission/blob/main/AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb
      - text: GitHub Repository
        icon: github
        href: https://github.com/VJMeyer/submission
    crossref:
      sec-prefix: "Section"
      fig-prefix: "Figure"
      tbl-prefix: "Table"
    callout-appearance: simple
    
  pdf:
    documentclass: book    # vs scrbook
    include-in-header: latex/preamble.tex
    pdf-engine: xelatex
    keep-tex: true
    toc: true
    toc-title: Table of Contents
    lof: true
    lot: true
    number-sections: true
    crossref:
      sec-prefix: "Section"
      fig-prefix: "Figure"
      tbl-prefix: "Table"
    include-before-body: latex/title-page.tex
    include-after-body: latex/affidavit.tex
    output-file: thesis-book.pdf
    cite-method: biblatex
    biblio-title: Bibliography
    geometry:
      - margin=2.5cm
      - paper=a4paper
    fontsize: 11pt
    # Chapter formatting
    top-level-division: chapter
    # Custom variables for chapter titles
    block-headings: true

bibliography: ref/MAref.bib






# # # SWITCH BETWEEN BOOK AND MAUSCRIPT QUARTO BY (UN-)COMMENTING THE RESPECTIVE SECTION IN THIS _quarto.yml file






# project:
#   type: book
#   output-dir: _outputs/book

# # Add this section to use our custom filter
# # filters:
# #   - _extensions/crossref-bridge.lua


# execute:
#   freeze: auto

# # crossref:
# #   sec-prefix: "Section"
# #   fig-prefix: "Figure"
# #   tbl-prefix: "Table"
# #   ref-hyperlink: true

# book:
#   title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
#   author: "Valentin Jakob Meyer"
# #  lof: true
# #  title-block-banner: true
# #  title-block-banner: latex/uni-bayreuth-logo.png
#   date: "2025-05-26"
#   search: true
#   repo-url: https://github.com/VJMeyer/submission
#   repo-actions: [edit]
#   downloads: [pdf, epub] #tex?
#   sharing: [twitter, facebook]
#   cover-image: images/cover.png
#   #output-file: "complete-book"
#   chapters:
#     - index.qmd
#     - chapters/Introduction.qmd
#     - chapters/Context.qmd
#     - chapters/AMTAIR.qmd
#     # - chapters/Implementation.qmd
#     - chapters/Discussion.qmd
#     - chapters/Conclusion.qmd
#     - chapters/Frontmatter.qmd
#     - ref/references.qmd
#   #  - lof.qmd
#   #  - AMTAIR_Prototype/data/example_rain-sprinkler-lawn/AMTAIR_Prototype_example_rain-sprinkler-lawn.ipynb
#   #  - AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb
#   appendices:
#     - chapters/Appendices.qmd
#     - chapters/appendixA.qmd
#   navbar:
#     pinned: true
#   page-footer: 
#     left: "Copyright 2025, Valentin Meyer" 
#     right: 
#       - icon: github
#         href: https://github.com/
#       - icon: twitter 
#         href: https://twitter.com/

# format:
#   html:
#     include-in-header:
#       text: |
#         <script src="https://hypothes.is/embed.js" async></script>
#     theme: cosmo
#     code-fold: true
#     toc: true
#     toc-depth: 5
#     toc-title: "ToC"
#     lof: true
#     page-navigation: true
#     site-path: /
#     self-contained: false
#     number-sections: true
#   #  crossref:
#   #    sec-prefix: "Section"
#   #  cite-method: citeproc
#   pdf:
#     documentclass: book
#     geometry: margin=1in
#     template: latex/template.tex
#     include-in-header: latex/preamble.tex
#     keep-tex: true
#     toc: true
#     lof: true
#     pdf-engine: xelatex
#     include-after-body: latex/affidavit.tex
#     output-file: thesis-book.pdf
#     cite-method: biblatex
#     biblio-title: Bibliography
#   #  crossref:
#   #    sec-prefix: "Section"
#   #   documentclass: book
#   #   crossref:
#   #     sec-prefix: "Section"
#   #   include-in-header: 
#   #     text: |
#   #       \usepackage{cleveref}
#   #       \crefformat{section}{#2Section~#1#3}
#   #       \usepackage{etoolbox}
#   #       \makeatletter
#   #       \patchcmd{\@sect}
#   #         {\addcontentsline{toc}{#1}{\ifnum #2>\c@secnumdepth \else
#   #            \protect\numberline{\csname the#1\endcsname}\fi
#   #            #8}}
#   #         {\ifx\@nodistcall\relax\addcontentsline{toc}{#1}{\ifnum #2>\c@secnumdepth \else
#   #            \protect\numberline{\csname the#1\endcsname}\fi
#   #            #8}\fi}
#   #         {}{}
#   #       \makeatother
#   #   geometry: margin=1in
#   #   template: latex/template.tex
#   # #  include-in-header: latex/preamble.tex
#   #   keep-tex: true
#   #   toc: true
#   #   lof: true
#   #   pdf-engine: xelatex
#   #   include-after-body: latex/affidavit.tex
#   #   output-file: thesis-book.pdf
#   #   cite-method: biblatex
#   # #  biblio-title: Bibliography    	
#   latex:
#     documentclass: book
#     include-in-header: latex/preamble.tex
#     include-after-body: latex/affidavit.tex
#     output-file: thesis-book.tex
#     keep-tex: true

#   docx: default

#   #jats: default

#   #odt: default

# bibliography: ref/MAref.bib





















# ## Common output settings
# # format-common: &format-common
# #   number-sections: true   # Enable section numbering
# #   toc: true              # Include table of contents
# #   toc-depth: 4           # Include headings up to level 4
# #   toc-title: "Contents"  # Custom TOC title
# #   # Customize section numbering
# #   include-in-header: 
# #     text: |
# #       \setcounter{secnumdepth}{4}
# #       \renewcommand{\thesection}{\arabic{section}}
# #       \renewcommand{\thesubsection}{\thesection.\arabic{subsection}}



# # Master configuration file for thesis project
# # Controls rendering formats and options

# # Configure which profile to use by uncommenting ONE of these sections
# # Then run: quarto render

# # MANUSCRIPT PROFILE - Interactive HTML with navigation
# project:
#   type: manuscript  # manuscript format for formal thesis
#   output-dir: _outputs/manuscript  # Output directory for manuscript format

# execute:
#   freeze: auto  # Caches results for faster rendering
# #  echo: false  # Hide code by default


# # Configure manuscript settings
# manuscript:
#   article: thesis.qmd  # Main entry point file
#   #downloads: [pdf, epub] #tex, MECA Bundle (.zip), MS Word?
#     # Explicitly list notebooks in desired order
#   notebooks:  # Include notebooks
#     - notebook: AMTAIR_Prototype/data/example_rain-sprinkler-lawn/AMTAIR_Prototype_example_rain-sprinkler-lawn.ipynb
#       title: AMTAIR Rain-Sprinkler-Lawn Example
#     #  url: https://colab.research.google.com/github/VJMeyer/submission/blob/main/AMTAIR_Prototype/data/example_rain-sprinkler-lawn/AMTAIR_Prototype_example_rain-sprinkler-lawn.ipynb
#     - notebook: AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb
#       title: AMTAIR Carlsmith Example
#     #  url: https://colab.research.google.com/github/VJMeyer/submission/blob/main/AMTAIR_Prototype/data/example_carlsmith/AMTAIR_Prototype_example_carlsmith.ipynb
#     #- notebook: notebooks/AMTAIR_Prototype_example_carlsmith.ipynb
#     #  title: AMTAIR Carlsmith Example
#     #  url:   https://github.com/VJMeyer/submission/blob/main/notebooks/AMTAIR_Prototype_example_carlsmithIPYNB.ipynb

# format:
#   html:
#     toc: true
#     toc-depth: 4
#     number-sections: true
#     toc-title: "Table of Contents"
#     lof: true
#     theme: cosmo
#     code-fold: true
#     #output-file: thesis-manuscript.html
#    ## PDF output settings
#   pdf:
#     documentclass: report  # Academic report format
#     classoption: [12pt, a4paper, oneside]  # Paper and font options
#     # template: latex/template.tex  # Custom template
#     # include-in-header: latex/preamble.tex  # LaTeX preamble
#     pdf-engine: xelatex  # Engine for PDF creation
#     keep-tex: true  # Keep LaTeX source
#     output-file: thesis-manuscript.pdf  # Output filename
#     toc: true  # Include table of contents
#     lot: true  # List of tables
#     lof: true  # List of figures
#     colorlinks: true  # Colored hyperlinks
#     include-after-body: latex/affidavit.tex


#   # # LaTeX source output
#   # latex:
#   #   documentclass: report  # Academic report format
#   #   include-in-header: latex/preamble.tex  # LaTeX preamble
#   #   output-file: thesis-manuscript.tex  # Output filename

# #  docx: default

# #  jats: default

# #  odt: default

# # Bibliography configuration
# bibliography: ref/MAref.bib  # Reference file location












# # Output format configuration
# # format:
# #   # HTML output settings
# #   html:
# #     <<: *format-common
# #     toc: true
# #     number-sections: true
# #   #  output-dir: _outputs/html/manuscript
# #     output-file: thesis-manuscript.html
#   #  toc: true  # Include table of contents
#   #  toc-depth: 5  # Depth of TOC headings
#   #  number-sections: false  # Number sections in output
#   #  site-path: /  # Base path for site


#   # pdf:
#   #   <<: *format-common
#   #   documentclass: report
#   #   classoption: [12pt, a4paper, oneside]
#   #   template: latex/template.tex
#   #   include-in-header: 
#   #     - latex/preamble.tex
#   #     - text: |
#   #         % Page numbering controls
#   #         \pagenumbering{roman}  % Front matter uses Roman numerals
          
#   #         % Command to switch to main text numbering
#   #         \newcommand{\startmain}{
#   #           \clearpage
#   #           \pagenumbering{arabic}  % Main text uses Arabic numerals
#   #           \setcounter{page}{1}    % Reset page counter
#   #         }
          
#   #         % Command for appendices numbering
#   #         \newcommand{\startappendix}{
#   #           \appendix
#   #           % Continue with Arabic numbers
#   #         }
#   #   # Insert commands at specific points in the document
#   #   include-before-body:
#   #     text: |
#   #       % This appears at the beginning of the document
#   #       % (front matter already using roman numerals)
    
#   #   include-after-body:
#   #     text: |
#   #       % This appears at the end of the document
    
#   #   keep-tex: true
#   #   output-dir: _outputs/pdf/manuscript
#   #   output-file: amtair-thesis-manuscript.pdf
  


