project:
  type: default
  output-dir: _outputs/manuscript
  # Use preview to avoid rebuilding everything during development
#  preview:
#    port: 4200
#    browser: false

# Shared execution settings
execute:
  freeze: auto  # Cache execution results

# Enable profiles for different output types
profiles:
  # Book format for interactive reading
  book:
    project:
      type: book
      output-dir: _outputs/book
    book:
      title: "Automating the Modelling of Transformative Artificial Intelligence Risks"
      author: "Valentin Jakob Meyer"
      date: "2025-05-26"
      search: true
      repo-url: https://github.com/VJMeyer/submission
      repo-actions: [edit]
      downloads: [pdf, epub, tex]
      sharing: [twitter, facebook]
      appendices: true
      cover-image: images/cover.png
      chapters:
        - index.qmd
        - chapters/Frontmatter.qmd
        - chapters/Introduction.qmd
        - chapters/Context.qmd
        - chapters/AMTAIR.qmd
        - chapters/Discussion.qmd
        - chapters/Conclusion.qmd
        - ref/references.qmd
        - chapters/Appendices.qmd
        - chapters/appendixA.qmd
      navbar:
        pinned: true
      page-footer: 
        left: "Copyright 2025, Valentin Meyer" 
        right: 
          - icon: github
            href: https://github.com/
          - icon: twitter 
            href: https://twitter.com/
    format:
      html:
        theme: cosmo
        code-fold: true
        toc: true
        toc-depth: 5
        toc-title: "ToC"
        page-navigation: true
      pdf:
        documentclass: book
        geometry: margin=1in
        template: latex/template.tex
        include-in-header: latex/preamble.tex
        keep-tex: true
        output-file: thesis-book.pdf
      latex:
        documentclass: book
        include-in-header: latex/preamble.tex
        output-file: thesis-book.tex
        keep-tex: true

  # Manuscript format for academic submission
  manuscript:
    project:
      type: manuscript
      output-dir: _outputs/manuscript  # Match default
    execute:
      echo: false
    manuscript:
      article: thesis.qmd
    format:
      html:
        toc: true
        toc-depth: 3
        number-sections: true
      pdf:
        documentclass: report
        classoption: [12pt, a4paper, oneside]
        template: latex/template.tex
        include-in-header: latex/preamble.tex
        pdf-engine: xelatex  # Use same engine across profiles
        keep-tex: true
        output-file: thesis-manuscript.pdf
        toc: true
        lot: true
        lof: true
        colorlinks: true
      latex:
        documentclass: report
        include-in-header: latex/preamble.tex
        output-file: thesis-manuscript.tex
        #keep-tex: true

# Shared bibliography configuration
bibliography: ref/MAref.bib