---
title: "Introduction"
# Control if this file starts numbering
numbering:
  start-at: 1      # Start at Section 1
  level: 1         # Chapter level
---


## Introduction


10% of Grade:

• introduces and motivates the core question or problem
• provides context for discussion (places issue within a larger debate or sphere of relevance)
• states precise thesis or position the author will argue for
• provides roadmap indicating structure and key content points of the essay

~ 14% of text ~ 4200 words


• introduces and motivates the core question or problem

## Motivation:  Problem Statement

## Motivation:  Research Question



• provides context for discussion (places issue within a larger debate or sphere of relevance)

## Scope:   Aim & Context of the Research

## Significance of the Research:    Theory of Change



• states precise thesis or position the author will argue for

## Thesis Statement & Position:    (Aim of the Paper)



• provides roadmap indicating structure and key content points of the essay

## Overview:    Structure & Approach of the Paper (Roadmap --- Theory of Change)

## Table of Contents